# Generated by Django 4.2.4 on 2023-09-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao_tarefa', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_tarefa', models.DateTimeField()),
                ('data_finalizacao_tarefa', models.DateTimeField(null=True)),
            ],
        ),
    ]
