# Generated by Django 4.2.4 on 2023-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_criacao_tarefa',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_entrega_tarefa',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_finalizacao_tarefa',
            field=models.DateField(null=True),
        ),
    ]
