# Generated by Django 4.2.5 on 2023-09-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_data_criacao_tarefa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_criacao_tarefa',
            field=models.DateField(auto_now=True),
        ),
    ]
